name: CI Pipeline
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: user
          MYSQL_PASSWORD: userpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Listar arquivos
        run: ls -la

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r ./app/requirements.txt

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Executar Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
        env:
          DB_HOST: mysql
          DB_USER: user
          DB_PASSWORD: userpass
          DB_NAME: mydatabase
          
      - name: Derrubar containers
        run: docker-compose down
