name: CI Pipeline
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: user
          MYSQL_PASSWORD: userpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Listar arquivos
        run: ls -la app/

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar Docker usando script oficial
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Buildar imagem Docker
        run: docker build -t app ./app

      - name: Rodar container
        run: |
          docker run -d -p 5000:5000 \
            --name container \
            -e DB_HOST=mysql \
            -e DB_USER=user \
            -e DB_PASSWORD=userpass \
            -e DB_NAME=mydatabase \
            meu-app

      - name: Derrubar container
        run: docker stop container && docker rm container
